// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6A7ufYM5-U7Dc8P2niv-JRdOHxBRW2UY',
    appId: '1:357795178335:web:0aa94f83e8ac72655578ea',
    messagingSenderId: '357795178335',
    projectId: 'chatapp-742ee',
    authDomain: 'chatapp-742ee.firebaseapp.com',
    storageBucket: 'chatapp-742ee.appspot.com',
    measurementId: 'G-HGNQLT68VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNxxx-MYaDNcR2AukvWs1YfPu1El3uoK4',
    appId: '1:357795178335:android:8c44d30f1b9318c35578ea',
    messagingSenderId: '357795178335',
    projectId: 'chatapp-742ee',
    storageBucket: 'chatapp-742ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHwB8eOMXdnnCRZn5Hw1pzvivUJFXkABo',
    appId: '1:357795178335:ios:254854b181edeeec5578ea',
    messagingSenderId: '357795178335',
    projectId: 'chatapp-742ee',
    storageBucket: 'chatapp-742ee.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHwB8eOMXdnnCRZn5Hw1pzvivUJFXkABo',
    appId: '1:357795178335:ios:c3318513686988365578ea',
    messagingSenderId: '357795178335',
    projectId: 'chatapp-742ee',
    storageBucket: 'chatapp-742ee.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
